# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vault.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vault.proto',
  package='vault',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bvault.proto\x12\x05vault\"[\n\tRequestDT\x12\x10\n\x03key\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x11\n\x04\x64\x65sc\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x10\n\x03val\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\x06\n\x04_keyB\x07\n\x05_descB\x06\n\x04_val\">\n\nResponseDT\x12\x0e\n\x06retval\x18\x01 \x01(\x05\x12\x14\n\x07retdesc\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_retdesc2\x9e\x01\n\x05Vault\x12/\n\x06insert\x12\x10.vault.RequestDT\x1a\x11.vault.ResponseDT\"\x00\x12\x30\n\x07\x63onsult\x12\x10.vault.RequestDT\x1a\x11.vault.ResponseDT\"\x00\x12\x32\n\tterminate\x12\x10.vault.RequestDT\x1a\x11.vault.ResponseDT\"\x00\x62\x06proto3'
)




_REQUESTDT = _descriptor.Descriptor(
  name='RequestDT',
  full_name='vault.RequestDT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='vault.RequestDT.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='desc', full_name='vault.RequestDT.desc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val', full_name='vault.RequestDT.val', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_key', full_name='vault.RequestDT._key',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_desc', full_name='vault.RequestDT._desc',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_val', full_name='vault.RequestDT._val',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=22,
  serialized_end=113,
)


_RESPONSEDT = _descriptor.Descriptor(
  name='ResponseDT',
  full_name='vault.ResponseDT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='retval', full_name='vault.ResponseDT.retval', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='retdesc', full_name='vault.ResponseDT.retdesc', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_retdesc', full_name='vault.ResponseDT._retdesc',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=115,
  serialized_end=177,
)

_REQUESTDT.oneofs_by_name['_key'].fields.append(
  _REQUESTDT.fields_by_name['key'])
_REQUESTDT.fields_by_name['key'].containing_oneof = _REQUESTDT.oneofs_by_name['_key']
_REQUESTDT.oneofs_by_name['_desc'].fields.append(
  _REQUESTDT.fields_by_name['desc'])
_REQUESTDT.fields_by_name['desc'].containing_oneof = _REQUESTDT.oneofs_by_name['_desc']
_REQUESTDT.oneofs_by_name['_val'].fields.append(
  _REQUESTDT.fields_by_name['val'])
_REQUESTDT.fields_by_name['val'].containing_oneof = _REQUESTDT.oneofs_by_name['_val']
_RESPONSEDT.oneofs_by_name['_retdesc'].fields.append(
  _RESPONSEDT.fields_by_name['retdesc'])
_RESPONSEDT.fields_by_name['retdesc'].containing_oneof = _RESPONSEDT.oneofs_by_name['_retdesc']
DESCRIPTOR.message_types_by_name['RequestDT'] = _REQUESTDT
DESCRIPTOR.message_types_by_name['ResponseDT'] = _RESPONSEDT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestDT = _reflection.GeneratedProtocolMessageType('RequestDT', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDT,
  '__module__' : 'vault_pb2'
  # @@protoc_insertion_point(class_scope:vault.RequestDT)
  })
_sym_db.RegisterMessage(RequestDT)

ResponseDT = _reflection.GeneratedProtocolMessageType('ResponseDT', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDT,
  '__module__' : 'vault_pb2'
  # @@protoc_insertion_point(class_scope:vault.ResponseDT)
  })
_sym_db.RegisterMessage(ResponseDT)



_VAULT = _descriptor.ServiceDescriptor(
  name='Vault',
  full_name='vault.Vault',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=180,
  serialized_end=338,
  methods=[
  _descriptor.MethodDescriptor(
    name='insert',
    full_name='vault.Vault.insert',
    index=0,
    containing_service=None,
    input_type=_REQUESTDT,
    output_type=_RESPONSEDT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='consult',
    full_name='vault.Vault.consult',
    index=1,
    containing_service=None,
    input_type=_REQUESTDT,
    output_type=_RESPONSEDT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='terminate',
    full_name='vault.Vault.terminate',
    index=2,
    containing_service=None,
    input_type=_REQUESTDT,
    output_type=_RESPONSEDT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VAULT)

DESCRIPTOR.services_by_name['Vault'] = _VAULT

# @@protoc_insertion_point(module_scope)
