# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import vault_pb2 as vault__pb2


class VaultStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.insert = channel.unary_unary(
                '/vault.Vault/insert',
                request_serializer=vault__pb2.RequestDT.SerializeToString,
                response_deserializer=vault__pb2.ResponseDT.FromString,
                )
        self.consult = channel.unary_unary(
                '/vault.Vault/consult',
                request_serializer=vault__pb2.RequestDT.SerializeToString,
                response_deserializer=vault__pb2.ResponseDT.FromString,
                )
        self.terminate = channel.unary_unary(
                '/vault.Vault/terminate',
                request_serializer=vault__pb2.RequestDT.SerializeToString,
                response_deserializer=vault__pb2.ResponseDT.FromString,
                )


class VaultServicer(object):
    """Missing associated documentation comment in .proto file."""

    def insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def consult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def terminate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VaultServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'insert': grpc.unary_unary_rpc_method_handler(
                    servicer.insert,
                    request_deserializer=vault__pb2.RequestDT.FromString,
                    response_serializer=vault__pb2.ResponseDT.SerializeToString,
            ),
            'consult': grpc.unary_unary_rpc_method_handler(
                    servicer.consult,
                    request_deserializer=vault__pb2.RequestDT.FromString,
                    response_serializer=vault__pb2.ResponseDT.SerializeToString,
            ),
            'terminate': grpc.unary_unary_rpc_method_handler(
                    servicer.terminate,
                    request_deserializer=vault__pb2.RequestDT.FromString,
                    response_serializer=vault__pb2.ResponseDT.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vault.Vault', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Vault(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vault.Vault/insert',
            vault__pb2.RequestDT.SerializeToString,
            vault__pb2.ResponseDT.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def consult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vault.Vault/consult',
            vault__pb2.RequestDT.SerializeToString,
            vault__pb2.ResponseDT.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def terminate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vault.Vault/terminate',
            vault__pb2.RequestDT.SerializeToString,
            vault__pb2.ResponseDT.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
